// Generated by CoffeeScript PHP 1.3.1
(function () {
    var findScroller, flipAnimationClass, flipAnimationSupport, flipedClass,
		flipedProperty, hilitRegister, hilitShow, inheritObject, overrideHandler, pickFileCounter, uploadingUrl,operationStore;

    ko.bindingHandlers.datetimepicker = {
        init: function (ele, valueAccessor) {
            var val = ko.utils.unwrapObservable(valueAccessor());
            val && $(ele).parent().data('datetimepicker').setValue(val);
            $(ele).parent().on('changeDate', function (e) {
                var time = ko.utils.unwrapObservable(valueAccessor());
                valueAccessor()($(ele).val());
                if(!time || Math.abs(e.localDate.valueOf() - new Date(time).valueOf()) >= 86400000){
                    $(ele).parent().data('datetimepicker').hide();
                }
            });
			$(ele).focus(function(){
				$(ele).parent().data('datetimepicker').show();
			})
            $("#edit").scroll(function(){
                $(ele).parent().data('datetimepicker').place();
            });
        }
    };
	var pullOutAnimationClass = "pass-pull-out";
	var pullDownAnimationClass = "pass-pull-down";
	var isAnimating = false;
	var currentType = "";
    ko.bindingHandlers.selectedType = {
        init: function (ele, valueAccessor) {
			var pass = $("#pass");
			pass.attr("class",model.className());
			var downAnimationEndFn = function(){
				pass.removeClass(pullDownAnimationClass);
				pass.parent().css('-webkit-perspective', '');
				isAnimating = false;
				pass.unbind('webkitAnimationEnd', downAnimationEndFn);
			};
			var outAnimationEndFn = function () {
				pass.removeClass(pullOutAnimationClass);
				pass.attr("class",model.className());
				pass.addClass(pullDownAnimationClass);
				pass.unbind('webkitAnimationEnd', outAnimationEndFn).bind('webkitAnimationEnd', downAnimationEndFn);
			};
            $(ele).on('click', '> dl', function () {
				var type = $(this).attr('data-value');
                valueAccessor()(type);
				if(currentType == type) return;
				currentType = type;
				if(!isAnimating){
					isAnimating = true;
					pass.parent().css('-webkit-perspective', '1000px');
					pass.addClass(pullOutAnimationClass);
					pass.bind('webkitAnimationEnd', outAnimationEndFn);
				}else{
					pass.attr("class",model.className());
					isAnimating = false;
				}
            });
        },
        update: function (ele, valueAccessor) {
            var val = ko.utils.unwrapObservable(valueAccessor());
			$(ele).children().removeClass('selected').filter('[data-value="' + val + '"]').addClass('selected');
        }
    };
	ko.bindingHandlers.checkedRadio = {
		init:function(element,valueAccessor){
			var value = ko.utils.unwrapObservable(valueAccessor());
			$(element).find("input[type=radio]:checked").prop("checked",false);
			$(element).find("input[type=radio][value="+value+"]").prop("checked",true);
			$(element).find("input[type=radio]").on("click",function(e){
				valueAccessor()($(element).find("input[type=radio]:checked").val());
			});
		}
	};
    ko.bindingHandlers.src = {
        update: function (element, valueAccessor) {
            var value;
            value = ko.utils.unwrapObservable(valueAccessor());
            return element.src = value || 'data:image/gif;base64,R0lGODlhAQABAIAAAP7//wAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==';
        }
    };

    ko.bindingHandlers.checkedValue = {
        init:function(element,valueAccessor){
            var value;
            $(element).on("blur",function(){
                value = ko.utils.unwrapObservable(valueAccessor());
                if(/\<|\>/gmi.test(value)){
                    alert("请不要输入特殊字符【<,>");
                    value = value.replace(/\<|\>/gmi,"");
                    valueAccessor()(value);
                }
            });
        }
    };
    var qrcode = null;
    ko.bindingHandlers.qrcode = {
        update: function (element, valueAccessor) {
            var value;
            value = ko.utils.unwrapObservable(valueAccessor());
            if (value != '') {
                var qrcodeContainer;
                if (!qrcode || $('canvas', element).length == 0 && $('table', element).length == 0) {
                    qrcodeContainer = $('<div class="qrcodeContainer"></div>').appendTo($(element));
                    qrcode = new QRCode(qrcodeContainer[0], {
                        width: 115,
                        height: 115
                    });
                }
                qrcode.clear();
                qrcode.makeCode(value);
            }
        }
    };
    function _isSupportCanvas() {
        return typeof CanvasRenderingContext2D != "undefined";
    }

    ko.bindingHandlers.barcode = {
        update: function (element, valueAccessor) {
            var value;
            value = ko.utils.unwrapObservable(valueAccessor());
            if (value != '') {
                var node = $(element), barcodeNode, renderer = _isSupportCanvas ? 'css' : 'css', settings = {
                    output: renderer,
                    barWidth: 1,
                    barHeight: 60
                };
                node.html('');
                if (renderer == 'canvas') {
//                  barcodeNode = $('<canvas class="barcodeContainer"></canvas>').appendTo(node);
                } else {
                    barcodeNode = $('<div class="barcodeContainer"></div>').appendTo(node);
                }
                barcodeNode.barcode(value, 'code39', settings);
            }
        }
    };
    function RGBToHex(rgb) {
        var color = rgb.replace(/(?:\(|\)|rgb|RGB)*/g, "").split(",");
        return '#' + ((1 << 24) | (parseInt(color[0]) << 16) | (parseInt(color[1]) << 8) | parseInt(color[2])).toString(16).substr(1);
    }
    function HexToRGB(hex){
        var color = (hex.replace("#","") ? hex.replace("#","").match(/([1-9a-f]{1,2})/g) : []) || [];
        return "rgb("+(color[0] ? parseInt(color[0],16) : 0)+","+(color[1] ? parseInt(color[1],16) : 0)+","+(color[2] ? parseInt(color[2],16) : 0)+")";
    }
    ko.bindingHandlers.pickColor = {
        init: function (element, valueAccessor) {
            var val = ko.utils.unwrapObservable(valueAccessor()).toLocaleLowerCase(),
                ele = $(element),
                icon = ele.next(".add-on").find("i");
            ele.attr('data-color', val).val(val);
            icon.css("background", val);
            //监听组件的颜色值变更
            ele.colorpicker().on('changeColor', function (e) {
                var o = e.color.toRGB(), rgb = 'rgb(' + o.r + ',' + o.g + ',' + o.b + ')';
                icon.css("background", rgb);
                valueAccessor()(rgb);
            });
            //监听用户输入的颜色值
            ele.on("keyup",function(e){
				var color = ele.val();
				if(color.indexOf("#") > -1){
					color = HexToRGB(color);
				}
                ele.colorpicker("setValue",color);
				valueAccessor()(color);
                icon.css("background", color);
            });
            //通过预览icon唤起颜色组件
            icon.click(function () {
                ele.colorpicker("show");
            });
            $("#edit").scroll(function(){
                ele.colorpicker("place");
            });
        }
    };

    pickFileCounter = 0;

    uploadingUrl = '/builder/builderJsonUpload.json';

    ko.bindingHandlers.pickFile = {
        init: function (element, valueAccessor) {
            var button, buttonText, del, display, el, input, parent, uploadFile, value, tool,role,edit;
            el = $(element);
            value = valueAccessor();
            parent = el.closest('.input-append');
			role = parent.attr("data-role");
            display = parent.find('input:text');//显示框 文件名或者是图片地址
            input = parent.find('input:file');
            button = parent.find('button');
            del = parent.find('a.btn-link[data-role=del]');
            edit = parent.find('a.btn-link[data-role=edit]');
            tool = parent.next('p.help-block');
            buttonText = button.text();

            //上传文件
            uploadFile = function (file, callback) {
                var fn, form, iframe, name;
                if (!(uploadingUrl != null)) {
                    fn = function () {
                        return callback('');
                    };
                    setTimeout(fn, 500);
                    return;
                }
                name = "pickFile_" + (++pickFileCounter);
                iframe = $('<iframe name="' + name + '" id="postiframe" style="display: none" />');
                $('body').append(iframe);
                form = el.closest('form');
                form.attr('action', uploadingUrl + "?imgId="+role);
                form.attr('method', 'post');
                form.attr('enctype', 'multipart/form-data');
                form.attr('encoding', 'multipart/form-data');
                form.attr('target', name);
                form.submit();
                return iframe.load(function () {
                    var elem, ret, text;
                    elem = iframe[0].contentWindow.document.body.childNodes[0];
                    text = elem.nodeType === 1 ? elem.childNodes[0] : elem;
                    if (ret = ko.utils.parseJson(text.nodeValue)) {
                        iframe.remove();
                        return callback(ret);
                    } else {
                        return typeof console !== "undefined" && console !== null ? console.error('upload failed') : void 0;
                    }
                });
            };
            setImagePreview =function(feils, setimgid, callback) {
                 //input
                 //var docObj = document.getElementById("transfer_img");
                 //img
                 var imgObjPreview = document.getElementById("preview"+setimgid);
                 //div
                 var divs = document.getElementById("localImag"+setimgid);
                 if (feils) {
                     //火狐下，直接设img属性
                     //imgObjPreview.src = docObj.files[0].getAsDataURL();
                     //火狐7以上版本不能用上面的getAsDataURL()方式获取，需要一下方式
                     imgObjPreview.src = window.URL.createObjectURL(feils);
                 } else {
                     //IE下，使用滤镜
                     docObj.select();
                     var imgSrc = document.selection.createRange().text;
                     var localImagId = document.getElementById("localImag"+setimgid);
                     //必须设置初始大小
                     //图片异常的捕捉，防止用户修改后缀来伪造图片
                     try {
                         localImagId.style.filter = "progid:DXImageTransform.Microsoft.AlphaImageLoader(sizingMethod=scale)";
                         localImagId.filters.item("DXImageTransform.Microsoft.AlphaImageLoader").src = imgSrc;
                     } catch (e) {
                         alert("您上传的图片格式不正确，请重新选择!");
                         return false;
                     }
                     imgObjPreview.style.display = 'none';
                     document.selection.empty();
                 }
                return callback();
             },
            //确认选择的文件框
            input.change(function () {
                var file;
                file = input.val() || '';
                if (!file) {
                    return;
                }
                display.val(file);
                button.prop('disabled', true);
                button.text('正在上传');
                return setImagePreview(input[0].files[0],button.attr("setimgid"),function(){
                    button.prop('disabled', false);
                    return button.text(buttonText);
                });
            });
            //点击选择文件
            button.add(display).click(function () {
                return input[0].click();
            });
            //删除事件
            del.click(function () {
				input.val("");
				display.val("");
                tool.text("");
                return value('');
            });
            //绑定输入框点击选择文件事件
            var displayClickEvent = function(isChooseFile){
                if(isChooseFile){
                    display.on("click",function(e){
                        return input[0].click();
                    });
                }else{
                    display.off("click");
                }

            };
            //displayClickEvent(true);
            /**编辑事件
             * 用户点击编辑按钮，dispaly框变为可编辑，解除绑定的点击唤起选择文件事件
             * 用户焦点离开display时：
             *      1.display变为仅读，校验用户输入的结果，
             *      2.合法则保存的输入，不合法则提示用户，并再次焦点display
             *      3.再次绑定点击唤起选择文件事件
             * */
            edit.click(function(e){
                display.focus().css("cursor","default").prop("readonly",false).val(value()).select();
                displayClickEvent(false);
                display.one("blur",function(e){
                    display.prop("readonly","readonly");
                    var url = display.val(),
                        oldUrl = value();
                    if(oldUrl != url || url == ""){
                        if(url){
                            value(url);
                            tool.text("");
                        }else{
                            value("");
                            display.val("");
                            tool.text("请输入图片地址或选择上传图片。");
                        }
                    }else{
                        display.val(url.replace(/^.+\//, ''));
                        tool.text("");
                    }
                    displayClickEvent(true);
                });
            });
         },
        update: function (element, valueAccessor) {
            var display, el, parent, url, value,tool;
            value = valueAccessor();
            url = value();
            el = $(element);
            parent = el.closest('.input-append');
            display = parent.find('input:text');
            tool = parent.next('p.help-block');
            url && display.val(url.replace(/^.+\//, ''));
            tool.text("");
        }
    };

    flipedClass = 'pass-fliped';

    flipedProperty = 'atBack';

    flipAnimationClass = 'pass-flip';

    flipAnimationSupport = window.WebKitCSSMatrix && 'm11' in new WebKitCSSMatrix();

    ko.bindingHandlers.flipBack = {
        init: function (element) {
            var elem;
            elem = $(element);
            return elem.bind('webkitAnimationEnd', function () {
                elem.removeClass(flipAnimationClass);
                return elem.parent().css('-webkit-perspective', '');
            });
        },
        update: function (element, valueAccessor, allBindings, viewModel) {
            var elem, showBack;
            elem = $(element);
            showBack = ko.utils.unwrapObservable(valueAccessor());
            if (showBack === elem.hasClass(flipedClass)) {
                return;
            }
            elem.parent().css('-webkit-perspective', '1000px');
            elem.toggleClass(flipedClass, showBack);
            elem.addClass(flipAnimationClass);
            viewModel[flipedProperty] = showBack;
            if (!flipAnimationSupport) {
                return elem.children('.pass-front').toggle(!showBack);
            }
        }
    };

    ko.bindingHandlers.hScroll = {
        init: function (element, valueAccessor, allBindings, viewModel) {
            var elem, iscroll;
            elem = $(element);
            iscroll = new iScroll(element, {
                snap: true,
                momentum: false,
                hScrollbar: false,
                onScrollEnd: function () {
                    var _base;
                    return typeof (_base = allBindings()).hScrollPage === "function" ? _base.hScrollPage(this.currPageX) : void 0;
                }
            });
            return elem.data('hScroll', iscroll);
        },
        update: function (element, valueAccessor) {
            var elem, items;
            elem = $(element);
            items = ko.utils.unwrapObservable(valueAccessor());
			var scroll = elem.data('hScroll');
			if(scroll.currPageX > items.length-1){
				scroll.currPageX = items.length-1;
			}
            elem.children(':first').css('width', items.length * elem.innerWidth() + 1);
            return elem.data('hScroll').refresh();
        }
    };
	ko.bindingHandlers.changeCurrentOperation = {
		init:function(element, valueAccessor){
			var ele = $(element);
			var items = ele.prev('.items');
			ele.on("click","> span",function(e){
				var index, scroll;
				if(!(scroll = items.data('hScroll'))) {
					return;
				}
				index = $(e.target).index();
				return scroll.scrollToPage(index, 0, 300);
			});
		}
	};
	operationStore = [];
	ko.bindingHandlers.siftOperation = {
		update:function(element, valueAccessor){
			var val = ko.utils.unwrapObservable(valueAccessor());
			var operations = model.operation.items();
			var formatArray = ["wave","text","qrcode","barcode"];
			//采用支付宝发码核销
			if(val == "true"){
				$.each(operations,function(i,n){
					var format = n.format();
					if($.inArray(format,formatArray) >= 0){
						operationStore.push(n);
					}
				});
				$.each(operationStore,function(i,n){
					model.operation.remove(n);
				});
			}else{
				$.each(operationStore,function(i,n){
					model.operation.append(n.export());
				});
				operationStore = [];
			}
		}
	}
    ko.bindingHandlers.hScrollpage = {
        update: function (element, valueAccessor) {
            var elem, page, scroll;
            elem = $(element);
            page = ko.utils.unwrapObservable(valueAccessor());
            if (!(scroll = elem.data('hScroll'))) {
                return;
            }
            if (scroll.currPageX !== page) {
                return scroll.scrollToPage(page, 0, 300);
            }
        }
    };

    ko.bindingHandlers.vScroll = {
        init: function (element) {
            var elem, iscroll;
            elem = $(element);
            iscroll = new iScroll(element, {
                vScrollbar: false
            });
            elem.data('vScroll', iscroll);
            return elem.on('mouseenter', function () {
                return elem.data('vScroll').refresh();
            });
        },
        update: function (element, valueAccessor) {
            ko.utils.unwrapObservable(valueAccessor());
            return $(element).data('vScroll').refresh();
        }
    };

    ko.bindingHandlers.sortable = {
        init: function (element, valueAccessor, allBindings) {
            var animateTop, drag, dragEnd, dragStart, exchange, exchangeChildren, getInfo;
            getInfo = function (e, shadow, offset) {
                var index, items;
                items = shadow.parent().children();
                index = items.index(shadow);
                return {
                    pageX: e.pageX,
                    pageY: e.pageY,
                    minY: index === 0 ? -Infinity : shadow.prev().offset().top + shadow.prev().outerHeight(),
                    maxY: index === items.length - 1 ? Infinity : shadow.next().offset().top,
                    shadow: shadow,
                    left: offset.left,
                    top: offset.top
                };
            };
            exchange = function (elem1, elem2) {
                elem1.insertAfter(elem2);
                animateTop(elem1, -elem2.outerHeight());
                return animateTop(elem2, elem1.outerHeight());
            };
            animateTop = function (elem, delta) {
                elem.css({
                    position: 'relative',
                    top: delta,
                    left: 0
                });
                return elem.animate({
                    top: 0
                }, 300, function () {
                    return elem.css({
                        position: ''
                    });
                });
            };
            dragStart = function (e) {
                var box, offset, shadow, width;
                box = $(e.dragTarget);
                box.data('startIndex', box.index());
                if (box.is(':only-child')) {
                    return false;
                }
                offset = box.offset();
                width = box.innerWidth();
                shadow = $('<div>');
                shadow.css({
                    backgroundColor: 'black',
                    opacity: 0.1,
                    height: box.outerHeight(),
                    marginBottom: box.css('margin-bottom'),
                    borderRadius: box.css('border-radius')
                });
                shadow.insertBefore(box);
                box.addClass('drag');
                box.css(offset);
                box.css({
                    width: width
                });
                box.appendTo(document.body);
                return box[0].info = getInfo(e, shadow, offset);
            };
            drag = function (e) {
                var box, dir, info, shadow, _ref;
                box = $(e.dragTarget);
                info = box[0].info;
                box.css({
                    left: info.left + e.pageX - info.pageX,
                    top: info.top + e.pageY - info.pageY
                });
                if ((info.minY < (_ref = e.pageY) && _ref < info.maxY)) {
                    return;
                }
                dir = e.pageY - info.minY;
                if (dir * (e.pageY - info.pageY) > 0) {
                    shadow = info.shadow;
                    if (dir > 0) {
                        exchange(shadow, shadow.next());
                    } else {
                        exchange(shadow.prev(), shadow);
                    }
                    return box[0].info = getInfo(e, shadow, box.offset());
                }
            };
            dragEnd = function (e) {
                var box, info, styles;
                box = $(e.dragTarget);
                info = box[0].info;
                styles = $.extend(info.shadow.offset(), {
                    opacity: 1
                });
                return box.animate(styles, 200, function () {
                    var endIndex, list, model, scrollTop;
                    scrollTop = document.body.scrollTop;
                    endIndex = info.shadow.index();
                    info.shadow.remove();
                    model = ko.dataFor(box[0]);
                    model.sorting = true;
                    setTimeout((function () {
                        return model.sorting = false;
                    }), 200);
                    ko.cleanNode(box[0]);
                    box[0].info = null;
                    box.remove();
                    list = valueAccessor();
                    list.remove(model);
                    list.splice(endIndex, 0, model);
                    return document.body.scrollTop = scrollTop;
                });
            };
            exchangeChildren = function (p, i, j) {
                var a, b, _ref;
                if (i > j) {
                    _ref = [j, i], i = _ref[0], j = _ref[1];
                }
                a = p.children().eq(i);
                b = p.children().eq(j);
                b.insertBefore(a);
                return a.remove().insertBefore(p.children().eq(j));
            };
            return $(element).drag(dragStart, drag, dragEnd);
        }
    };

    findScroller = function (elem) {
        var hScroll, vScroll;
        if (elem[0].parentNode === document.body) {
            return null;
        }
        if (hScroll = elem.data('hScroll')) {
            return {
                hScroll: hScroll,
                box: elem
            };
        }
        if (vScroll = elem.data('vScroll')) {
            return {
                vScroll: vScroll,
                box: elem
            };
        }
        return findScroller(elem.parent());
    };

    hilitShow = function (model, field, flag) {
        var arr, box, boxHeight, el, elem, elemHeight, elemTop, element, elements, fld, hScroll, index, list, maxScroll, page, targetY, vScroll, _i, _len, _ref, _ref1;
        if (flag == null) {
            flag = true;
        }
        if (!field) {
            return;
        }
        list = model._hilitList || [];
        elements = {};
        for (index = _i = 0, _len = list.length; _i < _len; index = ++_i) {
            arr = list[index];
            fld = arr[0], el = arr[1];
            if (fld === field) {
                elements[index] = el;
            }
        }
        element = null;
        for (index in elements) {
            el = elements[index];
            if ($(el).closest('body').length) {
                element = el;
            } else {
                list.splice(index, 1);
            }
        }
        elements = null;
        if (!element) {
            element = model._hilitBox;
            if (!element) {
                return;
            }
        }
        elem = $(element);
        elem.css('box-shadow', flag ? '0 0 8px #0088cc' : '');
        if (!flag) {
            return;
        }
        _ref1 = (_ref = findScroller(elem)) != null ? _ref : {}, hScroll = _ref1.hScroll, vScroll = _ref1.vScroll, box = _ref1.box;
        if (vScroll) {
            boxHeight = box.innerHeight();
            maxScroll = box.children().innerHeight() - boxHeight;
            if (maxScroll <= 0) {
                return;
            }
            elemTop = elem[0].offsetTop;
            elemHeight = elem.outerHeight();
            vScroll.refresh();

            targetY = -(elemTop + elemHeight) + boxHeight / 2;
            targetY > 0 ? targetY = 0 : null;
            targetY < -maxScroll ? targetY = -maxScroll : null;
            vScroll.scrollTo(0, targetY, 300);
        }
        if (hScroll) {
            while (!elem.hasClass('item')) {
                if (elem.length === 0) {
                    return;
                }
                elem = elem.parent();
            }
            page = Math.round(elem[0].offsetLeft / box.innerWidth());
            return hScroll.scrollToPage(page, 0, 300);
        }
    };

    hilitRegister = function (model, field, element) {
        var list;
        if (!field) {
            return;
        }
        list = model._hilitList || (model._hilitList = []);
        list.push([field, element]);
        return model._hilitBox = $(element).closest('.item')[0];
    };

    inheritObject = function (obj, overrides) {
        var ctor, key, ret, val;
        ctor = new Function;
        ctor.prototype = obj;
        ret = new ctor;
        for (key in overrides) {
            val = overrides[key];
            ret[key] = $.isFunction(val) ? $.proxy(val, ret) : val;
        }
        ret["super"] = function (name, args) {
            var _ref;
            return (_ref = obj[name]) != null ? _ref.apply(this, args) : void 0;
        };
        return ret;
    };

    overrideHandler = function (name, attrs) {
        return ko.bindingHandlers[name] = inheritObject(ko.bindingHandlers[name], attrs);
    };

    overrideHandler('value', {
        init: function (element, valueAccessor, allBindings, viewModel) {
            var elem;
            switch (element.tagName.toLowerCase()) {
                case 'input':
                case 'select':
                    elem = $(element);
                    elem.focus(function () {
                        return hilitShow(viewModel, allBindings().value);
                    });
                    elem.blur(function () {
                        return hilitShow(viewModel, allBindings().value, false);
                    });
            }
            return this["super"]('init', arguments);
        }
    });

    overrideHandler('text', {
        init: function (element, valueAccessor, allBindings, viewModel) {
            switch (element.tagName.toLowerCase()) {
                case 'div':
                case 'th':
                case 'td':
                    hilitRegister(viewModel, valueAccessor(), element);
            }
            return this["super"]('init', arguments);
        }
    });

}).call(this);
