var userGuideConfig = {
	completedStep:{
		basicInfo:{
			type:{
				path:"content.evoucherInfo.type",
				cnName:"模板"
			},
			product:{
				path:"content.evoucherInfo.product",
				cnName:"业务类型"
			},
			startDate:{
				path:"content.evoucherInfo.startDate",
				cnName:"生效日期"
			},
			endDate:{
				path:"content.evoucherInfo.endDate",
				cnName:"失效日期"
			},
			logoText:{
				path:"content.evoucherInfo.title",
				cnName:"标题"
			},
			logo:{
				path:"logo",
				cnName:"logo"
			}
		}
		/*"faceFields.headFields":{
			firstItem:{
				path:"content.evoucherInfo.einfo.headFields.0",
				cnName:"头部区块第一项"
			}
		},
		"faceFields.primaryFields":{
			firstItem:{
				path:"content.evoucherInfo.einfo.primaryFields.0",
				cnName:"第一区块第一项"
			},
			secondItem:{
				path:"content.evoucherInfo.einfo.primaryFields.1",
				cnName:"第一区块第二项"
			}
		}*/
	}
}